### PR TITLE
Upgrade operator SDK and Add Folder Sync feature

### PR DESCRIPTION
**Pull request by robertoeguia**
I apologize for the large pull request.

Changelog:
* Upgrade operator sdk from 1.5.2 to 1.36.0 as mentioned in #9 
* Reorganize files to match operator sdk project layout for easier maintainability
* Upgrade golang from 1.17 to 1.21
* Upgrade lastpass-cli to from 1.3.3-4 to use 1.5.0
* Build lastpass-cli binary as part of multi-stage docker build as newer versions are not provided in package repos
* Add image pull policy configuration in helm charts
* Add ability to sync entire lastpass folders #6

### CODE REVIEW

**Comment by niqdev** [comment]
@robertoeguia thanks for you contributions!

**Comment by niqdev** [comment]
@robertoeguia do you mind if I ask what's your use case? is this for personal development or work related? Are you interested in helping maintaining this project from time to time or at least getting involved in PR reviews?

**Comment by robertoeguia** [comment]
@niqdev I don't mind at all. This is for personal use and development. I am interested in maintaining and being involved in this project.

**Comment by niqdev** [comment]
sorry I missed the notification, that's great. as soon as I get a chance I'll setup the action to automatically release the latest docker image when changes are pushed in the main branch

**Pull request merged**
